name: update

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'mpv-easy/mpv-easy'
          latest: true
          fileName: '*'

      - name: update
        run: |
          ls -l