name: update

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'mpv-easy/mpv-easy'
          latest: true
          fileName: '*'

      - name: update
        run: |
          ls -l
          rm -rf .git

          git config --global init.defaultBranch main
          git config --global user.email "mpv-easy@mpv.com"
          git config --global user.name "mpv-easy-cdn"

          git init
          git remote add origin https://github.com/mpv-easy/mpv-easy-cdn.git

          git add .
          git commit -am "update by ci"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true
